server:
  http_port: ":8080"

database:
  master:
    host: "db"
    port: "5432"
    user: "postgres"
    pass: ""
    name: "images_db"
    ssl_mode: "disable"

  slaves: []

  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 30m

storage:
  endpoint: "play.min.io"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket_name: "image-bucket"
  use_ssl: true

kafka:
  group_id: "image-workers"
  topic: "image.uploaded"
  brokers:
    - "kafka:9092"
    - "kafka2:9093"
    - "kafka3:9094"

retry:
  attempts: 3
  delay: 500ms
  backoff: 2.0